# Generated by Django 2.2.5 on 2020-11-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CameraID', models.CharField(default='', max_length=70)),
                ('Camera_Name', models.CharField(default='', max_length=70)),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Src', models.URLField(default='')),
            ],
        ),
    ]
