# Generated by Django 2.2.5 on 2020-11-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdata',
            name='Src',
            field=models.CharField(default='', max_length=200),
        ),
    ]
